### Basic functions 
1. array
2. zeros
3. ones
4. empty
5. arange
6. reshape
7. linspace

In [1]:
import numpy as np


In [2]:
first_numpy_array=np.array([1,2,3,4])

In [3]:
print(first_numpy_array)

[1 2 3 4]


In [4]:
array_with_zeros=np.zeros((3,3))
array_with_zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [5]:
array_with_ones=np.ones((3,3))
array_with_ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [6]:
array_with_empty=np.empty((2,3))
array_with_empty

array([[-2.68156159e+154, -2.68156159e+154,  2.25827937e-314],
       [ 2.25828098e-314, -2.68156159e+154, -2.68156159e+154]])

In [7]:
np_arange=np.arange(12)
np_arange

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [8]:
np_arange.reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [9]:
np_arange.reshape(2,3,2)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [10]:
np_linspce=np.linspace(1,6,5)
np_linspce

array([1.  , 2.25, 3.5 , 4.75, 6.  ])

### Numpy Array : Shapes and Axes 

In [11]:
np.array(24) # zero dimensional array

array(24)

In [12]:
np.array([1,2,3,4]) # one dimensional array

array([1, 2, 3, 4])

In [13]:
np.array([[1,1,1],[1,2,1]]) # one dimensional array

array([[1, 1, 1],
       [1, 2, 1]])

In [14]:
A=np.array([[[1,1,1],[2,2,2],[3,3,3],[4,4,4]]])

In [15]:
A.shape

(1, 4, 3)

In [16]:
A.ndim

3

In [17]:
A.ndim

3

### Part-2

In [18]:
B= np.array([x for x in range(1,10)])
B

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
B.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
C= np.array([x for x in range(1,13)])

In [21]:
C.reshape(2,2,3)

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [22]:
C.reshape(3,2,2)

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [23]:
C.reshape(2,2,-1) #finds the 3rd needed dimension 

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [24]:
C.reshape(-1) # flatten

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

### Maths operations

In [25]:
A= np.array([[1,2,1],[2,2,3]])
B= np.array([3,4,5])

In [26]:
A

array([[1, 2, 1],
       [2, 2, 3]])

In [27]:
B

array([3, 4, 5])

In [28]:
np.add(A,B)

array([[4, 6, 6],
       [5, 6, 8]])

In [29]:
np.subtract(A,B)

array([[-2, -2, -4],
       [-1, -2, -2]])

In [30]:
np.multiply(A,B)

array([[ 3,  8,  5],
       [ 6,  8, 15]])

In [31]:
np.divide(A,B)

array([[0.33333333, 0.5       , 0.2       ],
       [0.66666667, 0.5       , 0.6       ]])

In [32]:
np.power(A,2)

array([[1, 4, 1],
       [4, 4, 9]])

In [33]:
np.power(A,B)

array([[  1,  16,   1],
       [  8,  16, 243]])

### Conditional Logic

In [34]:
x=np.array([i for i in range(10)])
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
np.where(x%2==0, 'Even', 'Odd')

array(['Even', 'Odd', 'Even', 'Odd', 'Even', 'Odd', 'Even', 'Odd', 'Even',
       'Odd'], dtype='<U4')

In [36]:
condlist =[x<5,x>5]
choicelist=[x**2,x**3]
np.select(condlist,choicelist,default=x)

array([  0,   1,   4,   9,  16,   5, 216, 343, 512, 729])

### Common maths and Stats Functions

In [37]:
arr=np.array([[4,3,2],[10,1,0],[5,8,24]])
arr

array([[ 4,  3,  2],
       [10,  1,  0],
       [ 5,  8, 24]])

In [38]:
np.amin(arr)

0

In [39]:
np.amin(arr,axis=0)

array([4, 1, 0])

In [40]:
np.amin(arr,axis=1)

array([2, 0, 5])

In [41]:
np.max(arr)

24

In [42]:
np.amax(arr,axis=0)

array([10,  8, 24])

In [43]:
np.amax(arr,axis=1)

array([ 4, 10, 24])

### Similar functions used with axis

In [44]:
np.median(arr)

4.0

In [45]:
np.mean(arr)

6.333333333333333

In [46]:
np.std(arr)

6.944222218666553

In [47]:
np.var(arr)

48.22222222222222

In [48]:
np.percentile(arr,50) # value under 50th percentile

4.0

In [49]:
deg=np.array([0,30,45,60,90])
np.sin(deg*np.pi/180) # similarly cos, tan

array([0.        , 0.5       , 0.70710678, 0.8660254 , 1.        ])

In [50]:
''' inverse trignometric functions
arcsin
arccos
arctan'''

' inverse trignometric functions\narcsin\narccos\narctan'

In [51]:
A= np.array([0.1,0.8,-2.2,-9.87])


In [52]:
np.floor(A)

array([  0.,   0.,  -3., -10.])

In [53]:
np.ceil(A)

array([ 1.,  1., -2., -9.])

### Indexing & Slicing

In [54]:
A1=np.array([1,2,3,4,5,6])
A2=np.array([[1,2,3],[4,5,6]])
A3=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

In [55]:
A1

array([1, 2, 3, 4, 5, 6])

In [56]:
A1[0]

1

In [57]:
A1[-3]

4

In [58]:
A2

array([[1, 2, 3],
       [4, 5, 6]])

In [59]:
A2[0,0]

1

In [60]:
A2[0,1]

2

In [61]:
A2[1,-1]

6

In [62]:
# Transponse
A2.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [63]:
np.transpose(A2)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [64]:
A3[0,1,2]

6

In [65]:
A3[1,1,-1]

12

In [66]:
A1[1:]

array([2, 3, 4, 5, 6])

In [67]:
A1[3:5]

array([4, 5])

In [68]:
A1[-3:-1]

array([4, 5])

In [69]:
A2[1,1:]

array([5, 6])

In [70]:
A2[-2:-3:-1]

array([[1, 2, 3]])

In [71]:
A3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [72]:
A3[0,1:,1:]

array([[5, 6]])

In [73]:
A3[1,1,0::2]

array([10, 12])